### ISSUE TITLE
Convert to use Whiskers

### ISSUE THREAD

**Issue by uncenter** [catppuccin/latex#4]
This is a tracking issue, following https://github.com/Keats/tera/issues/343. I attempted a conversion to a template before realizing that LaTeX's use of `{` and `}` characters - which are also the delimiters in the Tera language - makes templating very difficult.

**Comment by atticus-sullivan** [comment]
Yes that's pretty inconvenient. I started working on using whiskers for this still. Looking at workarounds for jinja, people seem to make the problematic parts string literals to be inserted. I'll make a PR soon so we can have a look if this works properly. With my lacking experience with whiskers+tera, I'm not quite sure how to handle version numbering etc. So I'm happy about any input.

**Comment by atticus-sullivan** [comment]
See https://github.com/catppuccin/latex/pull/14 (only a draft PR as some stuff, especially related to versioning, is still missing)
